**Basic numpy Tutorial**

In [7]:
import numpy as np
import torch

**Creating the Array in Numpy** 

In [3]:
one_dim=np.array([1,2,3,4,5])
print(one_dim)
print(type(one_dim))    

[1 2 3 4 5]
<class 'numpy.ndarray'>


**Creating 2d array but its type would be ndarray only .it does not matter you are creating 1,2,3d etc you will find ndarray only**

In [13]:
two_d=np.array([[[1,2,3],[4,5,6],[0,3,2]]])

print(two_d)

print(type(two_d))
print(two_d.shape)

[[[1 2 3]
  [4 5 6]
  [0 3 2]]]
<class 'numpy.ndarray'>
(1, 3, 3)


**Clarification on xsis and dimension and direction  in numpy**

In [20]:
arr = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

print(arr.shape)
print(arr.ndim)

(2, 2, 3)
3


- **Axis 0 → 2 blocks (depth)**
- **Axis 1 → 2 rows**
- **Axis 2 → 3 columns**
- **Axis 0 → stacking direction (front to back)**
- **Axis 1 → rows (top to bottom)**
- **Axis 2 → columns (left to right)**

**Creating the array from List in numpy**


In [ ]:
list=[1,2,3,4]
numarr=np.array(list,dtype=np.int32)
print(numarr)
print(numarr.dtype)
print(type(numarr))

[1 2 3 4]
int32
<class 'numpy.ndarray'>


**What is difference between array() and  asarray ()**

In [28]:
numarray=np.array([[1,1,3],[3,4,5]])
print(numarray)

asaaray=np.asarray(numarray)

print(asaaray)

[[1 1 3]
 [3 4 5]]
[[1 1 3]
 [3 4 5]]


**Different type of array in python**   

In [36]:
array0=np.array(20)  # array as scaler
print(array0)

oned=np.array([1,2,3,4]) #you can also create 1d array by using list
print(oned)

twodarray=np.array([[1,2,3],[4,5,6]]) #you can also create 2d array by using list of list
print(twodarray)

threed = np.array([
    [
        [1,2,3],
        [5,6,7],
        [8,9,10]
    ]
])

print(threed)
print(threed.shape)
print(threed.ndim)
print(threed)

20
[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 5  6  7]
  [ 8  9 10]]]
(1, 3, 3)
3
[[[ 1  2  3]
  [ 5  6  7]
  [ 8  9 10]]]


**accessing the elements in the array like 1,2,3,nd array**
**🧠 What Does (3, 2, 4) Mean?**

**Shape = (3, 2, 4)**

**Axis 0 → 3 blocks**

**Axis 1 → 2 rows per block**

**Axis 2 → 4 columns per row**

**You can visualize it like this:**

**Block 0:**
**[1 2 3 4]**
**[2 3 4 5]**

**Block 1:**
**[5 6 7 8]**
**[9 7 5 4]**

**Block 2:**
**[3 4 5 6]**
**[0 4 3 2]**

In [ ]:
yhreed=np.array(
    [
        [[1,2,3,4],[2,3,4,5]],
        [[5,6,7,8],[9,7,5,4]],
        [[3,4,5,6],[0,4,3,2]]
    ]


)

print(yhreed.shape)
print(yhreed.ndim)

print(yhreed[0][0][1]) # accessing 2 from 1depth in array, 1st row, 2nd column




(3, 2, 4)
3
2


**Negative indexing in the numpy**

In [46]:
fourdarray=np.array([
    
    [
    [
    [

        [1,2,3,4],[0,9,9,9]
    ],
    [
        [1,2,2,2],[1,1,1,1]
    ],
    [
        [4,5,6,7],[4,3,2,1]
    ],
    [
        [1,4,2,3],[6,4,3,2]
    ]
]
]
])

#printing 5 dimensional array

print(fourdarray)
print(fourdarray.ndim)

print(fourdarray[0][0][0][0][2]) # accessing 3 from 1st row, 1st column, 1st depth, 1st row, 3rd column

[[[[[1 2 3 4]
    [0 9 9 9]]

   [[1 2 2 2]
    [1 1 1 1]]

   [[4 5 6 7]
    [4 3 2 1]]

   [[1 4 2 3]
    [6 4 3 2]]]]]
5
3
