**slicing in the numpy   and  np.arange(start, stop).reshape(...)**

In [1]:
import numpy as np

In [ ]:
twod=np.arange(1,25).reshape(4,6)#  it is creating 1d array from 1 to 9 and reshape it to 4 rows and 6 columns.→ Converts that 1D array into a 2D array

print(twod)


threed=np.arange(1,25,2).reshape(2,3,2)#  it is creating 1d array from 1 to 9 and reshape it to 4 rows and 6 columns.→ Converts that 1D array into a 2D array

print(threed)





[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[[ 1  3]
  [ 5  7]
  [ 9 11]]

 [[13 15]
  [17 19]
  [21 23]]]


In [24]:
twod=np.array([
[
[1,2,3],
[4,5,6]
],
[
[4,5,6],
[8,9,10]
]
])

print(twod)

print(twod[0:0:2]   )

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 4  5  6]
  [ 8  9 10]]]
[]


**datatype code and datatype in numpy**

In [28]:
array=np.array([1,2,3,4],dtype=np.int32)

print(array.dtype.name) # it will print the name of the data type of the array

print(array.dtype.kind)  # checking the type of data in array


array2=np.array([5,3,2],dtype="i8") # it is creating an array of 8 byte integer
print(array2.dtype) # it will print the data type of the array


int32
i
int64


In [ ]:
array=np.array([1,2,3,4,5],dtype="S") # it is creating an array of string data type
print(array.dtype) # it will print the data type of the array

# |S1 means that the array is of string data type and each element can hold a string of length 1. So, in this case, 
# each element of the array can hold a single character string.| → byte order does not matter

|S1


**demo of astype() in numpy.it cast the array type from one data type to another**

In [33]:
arrayint=np.array([1,2,3,4,5],np.int32) # it is creating an array of integer data type
print(arrayint.dtype) # it will print the data type of the array

arrayf=arrayint.astype(np.float64) # it is creating an array of float data type

print(arrayf.dtype) # it will print the data type of the array
print(arrayf)

int32
float64
[1. 2. 3. 4. 5.]


**Reduce Memory Usage and  Float to Int (Truncation Demo) and Overflow Example and overflow example**

In [ ]:
array=np.array([1,2,3,4,5],dtype=np.int32)

print("before casting ",array.dtype,array.nbytes)

array2=array.astype(np.int8)

print("after casting",array2.dtype,array2.nbytes)

print("================================================================")


before casting  int32 20
after casting int8 5
